environment: REFORM_ENVIRONMENT
nodeEnvironment: NODE_ENV
gitRevision: GIT_REVISION
frontendPublicHttpProtocol: PUBLIC_PROTOCOL

service:
  name: icp-api

app:
  useCSRFProtection: "true"

idam:
  url: "http://localhost:5000"

s2s:
  url: "http://localhost:4502"
  microservice: "em_icp"
  secret: "AAAAAAAAAAAAAAAA"

tokenRefreshTime: 3600000 # (60 mins)

redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: 'false'
  secret: 'OVERWRITE_THIS'

security:
  referrerPolicy: "origin"

appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY

pact:
  pactBrokerUrl: PACT_BROKER_URL

health:
  timeout: 10000
  deadline: 15000
