environment: REFORM_ENVIRONMENT
nodeEnvironment: NODE_ENV
gitRevision: GIT_REVISION
frontendPublicHttpProtocol: PUBLIC_PROTOCOL

service:
  name: icp-api

app:
  useCSRFProtection: "true"

appInsights:
  instrumentationKey: "dummy_key"

health:
  timeout: 10000
  deadline: 15000

idam:
  url: "http://localhost:5000"

rateLimit:
  time: 15000
  max: 10

redis:
  host: 'localhost'
  port: 6379
  import: 'ioredis'

security:
  referrerPolicy: "origin"

s2s:
  url: "http://localhost:4502"
  microservice: "em_icp"
  secret: "AAAAAAAAAAAAAAAA"

tokenRefreshTime: 3600000 # (60 mins)
pact:
    branchName: "Dev"
    brokerUrl: "http://localhost:80"
    consumerVersion: ""